import type { Metadata } from "next";
import { Amatic_SC, Playfair_Display, Dancing_Script } from 'next/font/google';
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import Providers from './providers';

const inter = Amatic_SC({ subsets: ['hebrew', 'cyrillic', 'latin'], weight: ['700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}  bg-gray-50 dark:bg-black`}>
        <Providers>

        <Header />
        <main>{children}</main>
        <Footer />
        </Providers>
      </body>
    </html>
  );
}
